# -*- coding: utf-8 -*-
"""XK_IPMA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18iD_1z0xWYYwoeEPngCIk9ysaZ8uGaqU
"""
#!pip install clts_pcp --quiet
import os
import sys
import requests
import json
import clts_pcp as clts

tstart=clts.getts()


def detect_environment():
    clts.elapt["Detect Environment"]=clts.deltat(tstart)
    if "COLAB_RELEASE_TAG" in os.environ:
        return "colab"
    elif "RENDER" in os.environ:
        return "render"
    elif sys.platform.startswith("win"):
        return "windows"
    else:
        return "linux"

env = detect_environment()
clts.elapt[f"Environment Detected: {env}"]=clts.deltat(tstart)
print("Running in:", env)

if env == "colab":
    from google.colab import userdata
    EMAIL_FROM = userdata.get("EMAIL")
    EMAIL_PASSWORD = userdata.get("EMAIL_PASSWORD")

elif env == "render":
    EMAIL_FROM = os.getenv("EMAIL_FROM")
    RESEND_API_KEY = os.getenv("RESEND_API_KEY")

else:
    from dotenv import load_dotenv
    load_dotenv()

    EMAIL_FROM = os.getenv("EMAIL_FROM")
    EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")


clts.setcontext(f'IPMA Weather Station Data Retrieval - Environment: {env}')



url = 'https://api.ipma.pt/open-data/observation/meteorology/stations/obs-surface.geojson'


clts.elapt["Start Data Retrieval"]=clts.deltat(tstart)
response = requests.get(url)

if response.status_code == 200:
  data = response.json()
  print("Data retrieved successfully")
  print(f"Retrieved data from {len(data['features'])} stations")
  clts.elapt[f"Data Retrieved Successfully From {len(data['features'])} Stations"]=clts.deltat(tstart)
else:
  print(f"Failed to retrieve data {response.status_code}")
  clts.elapt[f"Data Retrieval Failed with Status Code {response.status_code}"]=clts.deltat(tstart)

for d in data['features']:
  if d['properties']['idEstacao'] == 1200545:
    single_station_data = d

print(single_station_data)

toemail = clts.listtimes()
print(toemail)

if env == "render":
    import resend
    resend.api_key = RESEND_API_KEY
    try:
        result = resend.Emails.send({
            "from": "Acme <onboarding@resend.dev>",
            "to": ["xavierkooijman@gmail.com"],
            "subject": "Hello from Resend Python!",
            "html": toemail,
        })

        print("Email sent successfully!")
        print(f"Email ID: {result['id']}") 
    except Exception as e:
        print(f"Error sending email: {e}")
        exit(1)

else:
   
    import smtplib
    from email.mime.text import MIMEText

    SMTP_SERVER = "smtp.gmail.com"
    SMTP_PORT = 587
    receiver = "xavierkooijman@gmail.com"

    try:
        msg = MIMEText(toemail, "html")
        msg["Subject"] = "Python Email Test"
        msg["From"] = EMAIL_FROM
        msg["To"] = receiver

        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls()
            server.login(EMAIL_FROM, EMAIL_PASSWORD)
            server.sendmail(EMAIL_FROM, receiver, msg.as_string())

        print("Email sent!")
    except Exception as e:
        print(f"Error sending email: {e}")